[package]
name = "flipperzero"
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
autobins = false
autotests = false
autobenches = false

[package.metadata.docs.rs]
default-target = "thumbv7em-none-eabihf"
targets = []
all-features = true

[lib]
bench = false
harness = false

[dependencies]
flipperzero-sys.workspace = true
flipperzero-test.workspace = true
ufmt.workspace = true

# Toolbox
digest = "0.10"

[dev-dependencies]
flipperzero-alloc.workspace = true
flipperzero-rt.workspace = true

# Toolbox
md-5 = { version = "0.10", default-features = false }
sha2 = { version = "0.10", default-features = false }

[features]
# enables features requiring an allocator
alloc = []

[[test]]
name = "dolphin"
harness = false

[[example]]
name = "dialog"
required-features = ["alloc"]
