name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - crates
          - examples/dialog
          - examples/gpio
          - examples/gui
          - examples/hello-rust
          - examples/notification
    uses: ./.github/workflows/_build_and_test.yml
    with:
      target: ${{ matrix.target }}
